# Generated by Django 2.2.6 on 2019-12-15 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorited_by', to='photos.Meme')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='profiles.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
