# Generated by Django 3.0.3 on 2020-02-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200225_1651'),
        ('profiles', '0002_auto_20200223_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(default=None, related_name='joined_by', to='groups.Group'),
        ),
    ]
