# Generated by Django 3.0.3 on 2020-02-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20200226_1242'),
        ('profiles', '0003_auto_20200225_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, default=None, related_name='joined_by', to='groups.Group'),
        ),
    ]
