# Generated by Django 3.0.3 on 2020-02-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_auto_20200227_1821'),
        ('profiles', '0004_auto_20200226_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reposts',
            field=models.ManyToManyField(blank=True, related_name='reposted_by', to='uploads.Image'),
        ),
    ]
