version: '3' 

services: 
  web:
    build: .
    #command: python /usr/src/django-memes/manage.py runserver 0.0.0.8000
    command: uwsgi --ini /code/uwsgi.ini
    volumes: 
      - .:/data 
    ports: 
      - 8000:8000
    tty: true
  
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - 80:80
    depends_on: 
      - web 
    tty: true

volumes:
  static_volume:
  media_volume: