# Generated by Django 3.0.3 on 2020-02-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['created'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='date_formed',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_members',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='grouppost',
            old_name='publication_date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_name',
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
