# Generated by Django 3.0.2 on 2020-01-17 10:59

from django.db import migrations, models
import uuid
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', versatileimagefield.fields.VersatileImageField(upload_to='uploads/', verbose_name='Upload')),
                ('photo_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('caption', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'images',
                'ordering': ['publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
