# Generated by Django 3.0.3 on 2020-02-23 14:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(default=None, upload_to='uploads/')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='profiles.Profile')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'images',
                'ordering': ['-publication_date'],
            },
        ),
    ]
