# Generated by Django 3.0.3 on 2020-02-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created'], 'verbose_name': 'Image', 'verbose_name_plural': 'images'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='publication_date',
            new_name='created',
        ),
    ]
