# Generated by Django 3.0.3 on 2020-02-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(default=None, height_field='400', upload_to='uploads/'),
        ),
    ]
