# Generated by Django 3.0.3 on 2020-02-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20200227_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(default=None, upload_to='uploads/'),
        ),
    ]
